import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Unused | Best Second-hand Clothes Out There </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&family=Playfair+Display&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Banner />
      </main>
    </div>
  );
};

export default Home;
